### ISSUE TITLE
Reduce the number of "No posts were found" messages

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#395]
**Is your feature request related to a problem? Please describe.**

On my test installation I have 3 posts, which means that on the News Blog home template there are  four "No posts were found" messages showing:
![image](https://github.com/user-attachments/assets/ef8be6f4-2565-42e9-8e39-9a6beae70401)

In my _opinion_ this feels too repetitive.

**Describe the solution you'd like**

Only show one "No Posts were found" message in this template.

**Comment by carolinan** [comment]
Related: https://github.com/WordPress/twentytwentyfive/pull/400

**Comment by jasmussen** [comment]
Is this addressed as of #427?

**Comment by carolinan** [comment]
In the templates that have a large number of queries, the number of visible messages are still the same yes?
In https://github.com/WordPress/twentytwentyfive/pull/400 @eliorivero had the idea to keep the blocks, but most of them would be placeholders.

My idea was to only show it on the front for the first query. If there are not enough posts in the first query, there are no posts to show in the following, either.

**Comment by jasmussen** [comment]
If we get no other improvements in, hopefully at least it will be an edgecase or encouragement to add some posts in those spaces.

**Comment by carolinan** [comment]
I don't feel that there is consensus on this, so let's not make any additional changes.
The user can delete the blocks too, if they need.
